services:
  postgres:
    build:
      context: .
      dockerfile: delivery-postgres.dockerfile
    container_name: ${PG_CONTAINER_NAME}
    image: 'delivery-db'
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  app:
    build:
      context: .
      dockerfile: delivery-app.dockerfile
    container_name: ${APP_CONTAINER_NAME}
    image: 'delivery-app'
    ports:
      - 8091:8080
    environment:
      APP_PORT: ${APP_PORT}
      DATASOURCE_URL: ${DATASOURCE_URL}
    depends_on:
      - postgres

volumes:
  postgres-data: