server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  file:
    name: ${LOG_PATH:delivery.log}

app:
  jwt:
    secret: ${JWT_SECRET:cThIIoDvwdueQB468K5xDc5633seEFoqwxjFDxSJyQQcThIIoDvwdueQB468K5xDc5633seEFoqwxjFDxSJyQQ}
    accessLifetimeMs: ${JWT_ACCESS_LIFETIME:1200000}
    refreshLifetimeMs: ${JWT_REFRESH_LIFETIME:1200000}
    issuer: ${JWT_ISSUER:delivery}